# Generated by Django 4.2 on 2023-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='changed',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
