# Generated by Django 4.2 on 2023-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_changed_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
